In [1]:
import numpy as np
import random as r

In [2]:
class Perceptron:
    __slots__ = 'bias', 'weights', 'output', 'inputs'
    
    def __init__(self):
        self.bias = r.random()
        self.weights = np.array([0])
        self.output = None
        
    def propagation(self, inputs):
        if not np.all(self.weights): self.weights = np.random.randn(inputs.size)
        self.output = 1 * ((self.weights.dot(inputs) - self.bias) > 0)
        self.inputs = inputs
        
    def update(self, lr, output):
        error = output - self.output 
        if error:
            self.weights = np.array(w + lr * error * x \
                                    for x, w in np.column_stack((self.inputs, self.weights)))
            self.bias = self.bias + lr * error

In [3]:
p = Perceptron()
p.propagation(np.array([1, 0, 0]))
p.output

1

In [4]:
p.update(.5, 1)

In [5]:
p.weights, p.bias

(array([ 2.66752276,  0.33316784, -0.28688303]), 0.39840231020653327)

In [6]:
p.propagation(np.array([1, 1, 0]))
p.output

1

In [7]:
p.update(.5, 1)
p.weights, p.bias

(array([ 2.66752276,  0.33316784, -0.28688303]), 0.39840231020653327)

In [10]:
p.propagation(np.array([0, 0, 0]))
p.output

0

In [11]:
p.update(.5, 0)
p.weights, p.bias

(array([ 2.66752276,  0.33316784, -0.28688303]), 0.39840231020653327)