In [1]:
%matplotlib inline

import numpy as np
import random as r
import matplotlib.pyplot as plt
from beautifultable import BeautifulTable

# Perceptron

In [2]:
class Perceptron:
    __slots__ = 'bias', 'weights', 'output', 'inputs'
    
    def __init__(self, size):
        self.bias = r.random()
        self.weights = np.random.randn(size)
        self.output = None
        self.inputs = None
        
    def propagation(self, inputs):
        self.output = 1 * ((self.weights.dot(inputs) + self.bias) > 0)
        self.inputs = inputs
        
    def update(self, lr, output):
        error = output - self.output 
        if error:
            self.weights = np.array([w + lr * error * x \
                                    for x, w in np.column_stack((self.inputs, self.weights))])
            self.bias = self.bias + lr * error
            
    def data(self):
        return [self.bias, self.weights, self.inputs, self.output]

In [3]:
table = BeautifulTable()
table.columns.header = ["epoch", "bias", "weights", "inputs", "outputs correct", "outputs"]

In [4]:
def data(epoch, data, output_correct):
    data.insert(0, epoch + 1)
    data.insert(4, output_correct)
    return data

In [5]:
def simulation(epochs, dataset, perceptron, table):
    weights_log = [perceptron.weights]
    bias_log = [perceptron.bias]
    
    for epoch in range(epochs):
        for i in range(len(dataset)):
            perceptron.propagation(dataset[i, 0:3])
            table.rows.append(data(epoch, perceptron.data(), dataset[i, 3]))
            perceptron.update(lr=0.5, output=dataset[i, 3])
        weights_log = np.concatenate((weights_log, [perceptron.weights]), axis=0)
        bias_log.append(perceptron.bias)
            
    return weights_log, bias_log

In [6]:
def plot(log, title):
    plt.plot(log[0][:, 0])
    plt.plot(log[0][:, 1])
    plt.plot(log[0][:, 2])
    plt.plot(log[1])
    plt.title(title)
    plt.xlabel('epocas')
    plt.legend(['Weight 1', 'Weight 2', 'Weight 3', 'Bias'], loc='upper left')
    plt.show()

## Caso Conjunción

In [7]:
conjunction = np.array([
    [1,1,1,1],
    [1,1,0,0],
    [1,0,1,0],
    [1,0,0,0],
    [0,1,1,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,0]
])

p_conjunction = Perceptron(3)

In [8]:
conjunction_log = simulation(30, conjunction, p_conjunction, table)

In [10]:
print(table)

+-------+--------+----------------------------+---------+------------+---------+
| epoch |  bias  |          weights           | inputs  | outputs co | outputs |
|       |        |                            |         |   rrect    |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.955  | [ 0.27668751 -0.76895915 - | [1 1 1] |     1      |    0    |
|       |        |        0.648997  ]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 1.455  | [ 0.77668751 -0.26895915 - | [1 1 0] |     0      |    1    |
|       |        |        0.148997  ]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.955  | [ 0.27668751 -0.76895915 - | [1 0 1] |     0      |    1    |
|       |        |        0.148997  ]         |         |            |         |
+-------+--------+----------

## Caso Disyunción

In [11]:
disjunction = np.array([
    [1,1,1,1],
    [1,1,0,1],
    [1,0,1,1],
    [1,0,0,1],
    [0,1,1,1],
    [0,1,0,1],
    [0,0,1,1],
    [0,0,0,0]
])

p_disjunction = Perceptron(3)

table = BeautifulTable()
table.columns.header = ["epoch", "bias", "weights", "inputs", "outputs correct", "outputs"]

In [12]:
simulation(30, disjunction, p_disjunction, table)

(array([[-0.51554646, -0.16569857, -1.38076807],
        [ 0.48445354,  0.33430143, -0.38076807],
        [ 0.48445354,  0.33430143, -0.38076807],
        [ 0.48445354,  0.33430143,  0.11923193],
        [ 0.48445354,  0.33430143,  0.11923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354,  0.33430143,  0.61923193],
        [ 0.48445354

In [13]:
print(table)

+-------+--------+----------------------------+---------+------------+---------+
| epoch |  bias  |          weights           | inputs  | outputs co | outputs |
|       |        |                            |         |   rrect    |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.344  | [-0.51554646 -0.16569857 - | [1 1 1] |     1      |    0    |
|       |        |        1.38076807]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.844  | [-0.01554646  0.33430143 - | [1 1 0] |     1      |    1    |
|       |        |        0.88076807]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.844  | [-0.01554646  0.33430143 - | [1 0 1] |     1      |    0    |
|       |        |        0.88076807]         |         |            |         |
+-------+--------+----------

## Bicondicionalidad

In [14]:
biconditionality = np.array([
    [1,1,1,1],
    [1,1,0,0],
    [1,0,1,0],
    [1,0,0,0],
    [0,1,1,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])

p_biconditionality = Perceptron(3)

table = BeautifulTable()
table.columns.header = ["epoch", "bias", "weights", "inputs", "outputs correct", "outputs"]

In [15]:
simulation(100, biconditionality, p_biconditionality, table)

(array([[ 1.17259226, -0.34970646,  0.89208537],
        [ 0.17259226, -0.84970646,  0.39208537],
        [-0.32740774, -0.84970646,  0.39208537],
        [-0.82740774, -0.84970646,  0.39208537],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774, -0.34970646, -0.10791463],
        [-0.82740774

In [16]:
print(table)

+-------+--------+----------------------------+---------+------------+---------+
| epoch |  bias  |          weights           | inputs  | outputs co | outputs |
|       |        |                            |         |   rrect    |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.329  | [ 1.17259226 -0.34970646   | [1 1 1] |     1      |    1    |
|       |        |        0.89208537]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | 0.329  | [ 1.17259226 -0.34970646   | [1 1 0] |     0      |    1    |
|       |        |        0.89208537]         |         |            |         |
+-------+--------+----------------------------+---------+------------+---------+
|   1   | -0.171 | [ 0.67259226 -0.84970646   | [1 0 1] |     0      |    1    |
|       |        |        0.89208537]         |         |            |         |
+-------+--------+----------

## Condicionalidad

In [17]:
conditionality = np.array([
    [1,1,1,1],
    [1,1,0,0],
    [1,0,1,1],
    [1,0,0,1],
    [0,1,1,1],
    [0,1,0,1],
    [0,0,1,1],
    [0,0,0,1]
])

p_conditionality = Perceptron(3)

table = BeautifulTable()
table.columns.header = ["epoch", "bias", "weights", "inputs", "outputs correct", "outputs"]

In [18]:
simulation(30, conditionality, p_conditionality, table)

(array([[-1.44355036, -0.7227551 ,  0.27229855],
        [-0.44355036, -0.2227551 ,  0.77229855],
        [-0.44355036, -0.7227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036, -1.2227551 ,  0.77229855],
        [-0.44355036

In [19]:
print(table)

+-------+-------+-----------------------------+---------+------------+---------+
| epoch | bias  |           weights           | inputs  | outputs co | outputs |
|       |       |                             |         |   rrect    |         |
+-------+-------+-----------------------------+---------+------------+---------+
|   1   | 0.235 | [-1.44355036 -0.7227551   0 | [1 1 1] |     1      |    0    |
|       |       |         .27229855]          |         |            |         |
+-------+-------+-----------------------------+---------+------------+---------+
|   1   | 0.735 | [-0.94355036 -0.2227551   0 | [1 1 0] |     0      |    0    |
|       |       |         .77229855]          |         |            |         |
+-------+-------+-----------------------------+---------+------------+---------+
|   1   | 0.735 | [-0.94355036 -0.2227551   0 | [1 0 1] |     1      |    1    |
|       |       |         .77229855]          |         |            |         |
+-------+-------+-----------